services:
  pg:
    user: root
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: vkwordle
      PGDATA: /data/postgres
    volumes:
      - ./postgres/content:/data/postgres
    ports:
      - "5532:5432"
    restart: unless-stopped